name: Update to POST_README.md

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build:
    if: ${{ github.run_number == 1 }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure user profile
        run: |
          git config user.email "${{ format('@{0}', github.actor) }}"
          git config user.name "${{ format('@{0}', github.actor) }}"

      - run: mv POST_README.md README.md
      - run: rm .github/workflows/post-readme.yml
      
      - name: Commit and push
        run: |
          git add --all
          git commit --message "Update README.md"
          git push --set-upstream origin ${{ github.event.inputs.target-branch }}
