name: Set up scaffold

on:
  workflow_dispatch:
    inputs:
      target-branch:
        description: Target new branch
        default: main
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure user profile
        run: |
          git config user.email "${{ format('@{0}', github.actor) }}"
          git config user.name "${{ format('@{0}', github.actor) }}"

      - name: Create new branch "${{ github.event.inputs.target-branch }}"
        # Only create the new branch if we are not replacing ourselves.
        if: ${{ format('refs/heads/{0}', github.event.inputs.target-branch) != github.ref }}
        run: git checkout -b ${{ github.event.inputs.target-branch }}

      # create-react-app will complain if ".github" directory exists.
      # In case we want to add other workflows for deployment, we need to rename/merge.
      - name: Rename ".github"
        run: |
          rm .github/workflows/set-up-scaffold.yml
          mv .github/ /tmp/dot-github-merge

      - name: Run `create-react-app`
        run: npx create-react-app .
      
      - name: Run `npm audit`
        run: |
          npm install --package-lock-only
          npm audit fix
      
      - name: Merge ".github"
        run: |
          cp -r /tmp/dot-github-merge/* .github
          rm -r /tmp/dot-github-merge/

      - name: Commit and push
        run: |
          git add --all
          git commit --message "Initial scaffold"
          git push --set-upstream origin ${{ github.event.inputs.target-branch }}
