on:
  push:
    branches: [main]

jobs:
  setup:
    if: ${{ github.run_number == 1 && github.repository != 'compulim/template-create-react-app' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure user profile
        run: |
          git config user.email "${{ format('@{0}', github.actor) }}"
          git config user.name "${{ format('@{0}', github.actor) }}"

      - run: |
          mv README.scaffold.md README.md
          git add --all
          git commit --message "Showing README.scaffold.md"
          git push --set-upstream origin ${{ github.event.inputs.target-branch }}

      - name: Show README.post.md
        run: mv README.post.md README.md

      # create-react-app will complain if ".github" directory exists.
      # In case we want to add other workflows for deployment, we need to rename/merge.
      - name: Rename ".github"
        run: |
          rm ${{ github.workflow }}
          mv .github/ /tmp/dot-github-merge

      - name: Run `create-react-app`
        run: npx create-react-app .

      - name: Run `npm audit`
        continue-on-error: true
        run: |
          npm install --package-lock-only
          npm audit fix

      - name: Merge ".github"
        run: |
          cp -r /tmp/dot-github-merge/ .github/
          rm -r /tmp/dot-github-merge/

      - name: Show README.post.md
        run: |
          mv README.md README.create-react-app.md
          mv README.old.md README.md

      - name: Commit and push
        run: |
          git add --all
          git commit --message "Initial `create-react-app` scaffold"
          git push --set-upstream origin ${{ github.event.inputs.target-branch }}

      - name: Set up empty `gh-pages` branch
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          git commit --all --allow-empty --message "Set up empty branch"
          git push --set-upstream origin gh-pages
